version: '3.9'
services:
  db:
    container_name: mysql_container
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: lab
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - "3308"
    networks:
      - demo-network
  lab:
    container_name: lab_container
    image: luca00r/lab
    restart: always
    build: ./rest-person-with-spring-boot-and-java
    working_dir: /rest-person-with-spring-boot-and-java
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/lab?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge